# Weather Project

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv(r"C:\Users\MAYURI\Downloads\weather.csv")

In [4]:
data

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# head

In [12]:
data.head(2)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes

# .shape

In [13]:
data.shape

(366, 22)

# index

In [14]:
data.index

RangeIndex(start=0, stop=366, step=1)

# columns

In [15]:
data.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

# dtypes

In [16]:
data.dtypes

MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

# .unique()

In [23]:
data['Humidity3pm'].unique()

array([29, 36, 69, 56, 49, 57, 47, 48, 32, 34, 35, 20, 16, 22, 23, 26, 25,
       27, 72, 79, 31, 55, 80, 90, 46, 60, 40, 63, 54, 74, 42, 24, 37, 51,
       86, 43, 62, 52, 64, 44, 30, 18, 14, 45, 28, 88, 71, 58, 38, 76, 41,
       73, 78, 39, 33, 15, 17, 68, 93, 50, 65, 53, 67, 70, 94, 59, 96, 85,
       66, 87, 82, 61, 21, 13], dtype=int64)

In [22]:
data.head(2)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes

# .nunique()

In [24]:
data.nunique()

MinTemp          180
MaxTemp          187
Rainfall          47
Evaporation       55
Sunshine         114
WindGustDir       16
WindGustSpeed     35
WindDir9am        16
WindDir3pm        16
WindSpeed9am      22
WindSpeed3pm      26
Humidity9am       60
Humidity3pm       74
Pressure9am      190
Pressure3pm      193
Cloud9am           9
Cloud3pm           9
Temp9am          178
Temp3pm          200
RainToday          2
RISK_MM           47
RainTomorrow       2
dtype: int64

# .count "show all null values"

In [26]:
data.count

<bound method DataFrame.count of      MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW
1       14.0     26.9       3.6          4.4       9.7         ENE
2       13.7     23.4       3.6          5.8       3.3          NW
3       13.3     15.5      39.8          7.2       9.1          NW
4        7.6     16.1       2.8          5.6      10.6         SSE
..       ...      ...       ...          ...       ...         ...
361      9.0     30.7       0.0          7.6      12.1         NNW
362      7.1     28.4       0.0         11.6      12.7           N
363     12.5     19.9       0.0          8.4       5.3         ESE
364     12.5     26.9       0.0          5.0       7.1          NW
365     12.3     30.2       0.0          6.0      12.6          NW

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29
1             39.0          E          W           4.0  ...           36
2             85.0          N        NNE           6.0  ...           69
3             54.0        WNW          W          30.0  ...           56
4             50.0        SSE        ESE          20.0  ...           49
..             ...        ...        ...           ...  ...          ...
361           76.0        SSE         NW           7.0  ...           15
362           48.0        NNW        NNW           2.0  ...           22
363           43.0        ENE        ENE          11.0  ...           47
364           46.0        SSW        WNW           6.0  ...           39
365           78.0         NW        WNW          31.0  ...           13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6
1         1012.4       1008.4         5         3     17.5     25.7
2         1009.5       1007.2         8         7     15.4     20.2
3         1005.5       1007.0         2         7     13.5     14.1
4         1018.3       1018.5         7         7     11.1     15.4
..           ...          ...       ...       ...      ...      ...
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM RainTomorrow
0           No      3.6          Yes
1          Yes      3.6          Yes
2          Yes     39.8          Yes
3          Yes      2.8          Yes
4          Yes      0.0           No
..         ...      ...          ...
361         No      0.0           No
362         No      0.0           No
363         No      0.0           No
364         No      0.0           No
365         No      0.0           No

[366 rows x 22 columns]>

# .value_counts
"Show all unique values with count"

In [28]:
data.value_counts

<bound method DataFrame.value_counts of      MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW
1       14.0     26.9       3.6          4.4       9.7         ENE
2       13.7     23.4       3.6          5.8       3.3          NW
3       13.3     15.5      39.8          7.2       9.1          NW
4        7.6     16.1       2.8          5.6      10.6         SSE
..       ...      ...       ...          ...       ...         ...
361      9.0     30.7       0.0          7.6      12.1         NNW
362      7.1     28.4       0.0         11.6      12.7           N
363     12.5     19.9       0.0          8.4       5.3         ESE
364     12.5     26.9       0.0          5.0       7.1          NW
365     12.3     30.2       0.0          6.0      12.6          NW

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29
1             39.0          E          W           4.0  ...           36
2             85.0          N        NNE           6.0  ...           69
3             54.0        WNW          W          30.0  ...           56
4             50.0        SSE        ESE          20.0  ...           49
..             ...        ...        ...           ...  ...          ...
361           76.0        SSE         NW           7.0  ...           15
362           48.0        NNW        NNW           2.0  ...           22
363           43.0        ENE        ENE          11.0  ...           47
364           46.0        SSW        WNW           6.0  ...           39
365           78.0         NW        WNW          31.0  ...           13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6
1         1012.4       1008.4         5         3     17.5     25.7
2         1009.5       1007.2         8         7     15.4     20.2
3         1005.5       1007.0         2         7     13.5     14.1
4         1018.3       1018.5         7         7     11.1     15.4
..           ...          ...       ...       ...      ...      ...
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM RainTomorrow
0           No      3.6          Yes
1          Yes      3.6          Yes
2          Yes     39.8          Yes
3          Yes      2.8          Yes
4          Yes      0.0           No
..         ...      ...          ...
361         No      0.0           No
362         No      0.0           No
363         No      0.0           No
364         No      0.0           No
365         No      0.0           No

[366 rows x 22 columns]>

# .info

In [29]:
data.info

<bound method DataFrame.info of      MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW
1       14.0     26.9       3.6          4.4       9.7         ENE
2       13.7     23.4       3.6          5.8       3.3          NW
3       13.3     15.5      39.8          7.2       9.1          NW
4        7.6     16.1       2.8          5.6      10.6         SSE
..       ...      ...       ...          ...       ...         ...
361      9.0     30.7       0.0          7.6      12.1         NNW
362      7.1     28.4       0.0         11.6      12.7           N
363     12.5     19.9       0.0          8.4       5.3         ESE
364     12.5     26.9       0.0          5.0       7.1          NW
365     12.3     30.2       0.0          6.0      12.6          NW

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29
1             39.0          E          W           4.0  ...           36
2             85.0          N        NNE           6.0  ...           69
3             54.0        WNW          W          30.0  ...           56
4             50.0        SSE        ESE          20.0  ...           49
..             ...        ...        ...           ...  ...          ...
361           76.0        SSE         NW           7.0  ...           15
362           48.0        NNW        NNW           2.0  ...           22
363           43.0        ENE        ENE          11.0  ...           47
364           46.0        SSW        WNW           6.0  ...           39
365           78.0         NW        WNW          31.0  ...           13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6
1         1012.4       1008.4         5         3     17.5     25.7
2         1009.5       1007.2         8         7     15.4     20.2
3         1005.5       1007.0         2         7     13.5     14.1
4         1018.3       1018.5         7         7     11.1     15.4
..           ...          ...       ...       ...      ...      ...
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM RainTomorrow
0           No      3.6          Yes
1          Yes      3.6          Yes
2          Yes     39.8          Yes
3          Yes      2.8          Yes
4          Yes      0.0           No
..         ...      ...          ...
361         No      0.0           No
362         No      0.0           No
363         No      0.0           No
364         No      0.0           No
365         No      0.0           No

[366 rows x 22 columns]>

# Find all unique "windSpeed(3pm and 9am)"values in data?

In [30]:
data.head(2)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes

In [31]:
data.nunique()

MinTemp          180
MaxTemp          187
Rainfall          47
Evaporation       55
Sunshine         114
WindGustDir       16
WindGustSpeed     35
WindDir9am        16
WindDir3pm        16
WindSpeed9am      22
WindSpeed3pm      26
Humidity9am       60
Humidity3pm       74
Pressure9am      190
Pressure3pm      193
Cloud9am           9
Cloud3pm           9
Temp9am          178
Temp3pm          200
RainToday          2
RISK_MM           47
RainTomorrow       2
dtype: int64

In [32]:
data["WindSpeed9am"].nunique()

22

In [34]:
data["WindSpeed3pm"].nunique()

26

In [35]:
data["WindSpeed3pm"].unique()

array([20, 17,  6, 24, 28, 26,  9, 15,  7, 19, 11, 13, 31, 22, 35, 30, 48,
        4, 37, 33,  0,  2, 39, 52, 41, 50], dtype=int64)

In [36]:
data["WindSpeed9am"].unique()

array([ 6.,  4., 30., 20., 19., 11.,  7.,  2., 13.,  9., 15., 22., 41.,
       24., 17., nan,  0., 26., 33., 31., 28., 39., 35.])

# Find the no.of times when "rain tomorrow is yes"

In [46]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [42]:
data.RainTomorrow.value_counts()

No     300
Yes     66
Name: RainTomorrow, dtype: int64

In [47]:
data[data.RainTomorrow=="No"]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [48]:
data[data.RainTomorrow=="Yes"]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,3.2,21.9,0.0,6.8,5.2,NW,80.0,SSE,NW,2.0,...,50,1012.1,1006.5,1,8,15.9,21.0,No,17.4,Yes
337,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,31.0,...,22,1016.3,1011.8,1,1,22.5,28.4,No,7.6,Yes
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
340,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,24.0,...,40,1009.5,1005.3,5,4,12.8,16.2,No,8.2,Yes
347,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,6.0,...,47,1020.9,1016.0,4,7,16.3,23.2,No,13.2,Yes

# Yes value get from groupby() function

In [49]:
data.groupby("RainTomorrow").get_group("Yes")

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,3.2,21.9,0.0,6.8,5.2,NW,80.0,SSE,NW,2.0,...,50,1012.1,1006.5,1,8,15.9,21.0,No,17.4,Yes
337,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,31.0,...,22,1016.3,1011.8,1,1,22.5,28.4,No,7.6,Yes
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
340,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,24.0,...,40,1009.5,1005.3,5,4,12.8,16.2,No,8.2,Yes
347,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,6.0,...,47,1020.9,1016.0,4,7,16.3,23.2,No,13.2,Yes

# Q.3 find the no.of times when the "cloud9am" exactly 7

In [15]:
data[data["Cloud9am"]==7]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,0.7,14.1,0.0,5.6,9.0,ENE,20.0,SSW,NNW,6.0,...,43,1026.7,1022.1,7,1,7.4,13.7,No,0.0,No
327,7.8,16.2,17.4,6.4,7.9,NW,50.0,NW,N,15.0,...,44,1016.7,1017.8,7,1,8.0,14.3,Yes,0.0,No
348,11.9,21.1,13.2,6.6,NaN,NW,41.0,NNE,N,7.0,...,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No
349,9.2,19.6,0.6,3.4,10.4,ENE,31.0,SSE,NNW,4.0,...,42,1022.3,1019.7,7,4,11.6,18.4,No,0.0,No
355,9.0,20.6,0.0,9.0,6.2,ENE,39.0,S,SW,11.0,...,28,1022.3,1018.6,7,5,11.4,18.5,No,0.8,No

In [13]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

# Q.5 rename the column name "Sunshine"to "Sunlight"

In [23]:
data.rename(columns = {'Sunshine':'Sunlight'})

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunlight,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# Q.4 find out all the null value in data

In [24]:
data.isnull().sum()

MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          3
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64

In [26]:
data.notnull().sum()

MinTemp          366
MaxTemp          366
Rainfall         366
Evaporation      366
Sunshine         363
WindGustDir      363
WindGustSpeed    364
WindDir9am       335
WindDir3pm       365
WindSpeed9am     359
WindSpeed3pm     366
Humidity9am      366
Humidity3pm      366
Pressure9am      366
Pressure3pm      366
Cloud9am         366
Cloud3pm         366
Temp9am          366
Temp3pm          366
RainToday        366
RISK_MM          366
RainTomorrow     366
dtype: int64

# Q.6 what is the mean "Max Temp"

In [29]:
data.head

<bound method NDFrame.head of      MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW
1       14.0     26.9       3.6          4.4       9.7         ENE
2       13.7     23.4       3.6          5.8       3.3          NW
3       13.3     15.5      39.8          7.2       9.1          NW
4        7.6     16.1       2.8          5.6      10.6         SSE
..       ...      ...       ...          ...       ...         ...
361      9.0     30.7       0.0          7.6      12.1         NNW
362      7.1     28.4       0.0         11.6      12.7           N
363     12.5     19.9       0.0          8.4       5.3         ESE
364     12.5     26.9       0.0          5.0       7.1          NW
365     12.3     30.2       0.0          6.0      12.6          NW

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29
1             39.0          E          W           4.0  ...           36
2             85.0          N        NNE           6.0  ...           69
3             54.0        WNW          W          30.0  ...           56
4             50.0        SSE        ESE          20.0  ...           49
..             ...        ...        ...           ...  ...          ...
361           76.0        SSE         NW           7.0  ...           15
362           48.0        NNW        NNW           2.0  ...           22
363           43.0        ENE        ENE          11.0  ...           47
364           46.0        SSW        WNW           6.0  ...           39
365           78.0         NW        WNW          31.0  ...           13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6
1         1012.4       1008.4         5         3     17.5     25.7
2         1009.5       1007.2         8         7     15.4     20.2
3         1005.5       1007.0         2         7     13.5     14.1
4         1018.3       1018.5         7         7     11.1     15.4
..           ...          ...       ...       ...      ...      ...
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM RainTomorrow
0           No      3.6          Yes
1          Yes      3.6          Yes
2          Yes     39.8          Yes
3          Yes      2.8          Yes
4          Yes      0.0           No
..         ...      ...          ...
361         No      0.0           No
362         No      0.0           No
363         No      0.0           No
364         No      0.0           No
365         No      0.0           No

[366 rows x 22 columns]>

In [30]:
data.MaxTemp.mean()

20.55027322404372

# Q7 what is the Standard Deviation of "Evapuration"

In [31]:
data.head

<bound method NDFrame.head of      MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW
1       14.0     26.9       3.6          4.4       9.7         ENE
2       13.7     23.4       3.6          5.8       3.3          NW
3       13.3     15.5      39.8          7.2       9.1          NW
4        7.6     16.1       2.8          5.6      10.6         SSE
..       ...      ...       ...          ...       ...         ...
361      9.0     30.7       0.0          7.6      12.1         NNW
362      7.1     28.4       0.0         11.6      12.7           N
363     12.5     19.9       0.0          8.4       5.3         ESE
364     12.5     26.9       0.0          5.0       7.1          NW
365     12.3     30.2       0.0          6.0      12.6          NW

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29
1             39.0          E          W           4.0  ...           36
2             85.0          N        NNE           6.0  ...           69
3             54.0        WNW          W          30.0  ...           56
4             50.0        SSE        ESE          20.0  ...           49
..             ...        ...        ...           ...  ...          ...
361           76.0        SSE         NW           7.0  ...           15
362           48.0        NNW        NNW           2.0  ...           22
363           43.0        ENE        ENE          11.0  ...           47
364           46.0        SSW        WNW           6.0  ...           39
365           78.0         NW        WNW          31.0  ...           13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6
1         1012.4       1008.4         5         3     17.5     25.7
2         1009.5       1007.2         8         7     15.4     20.2
3         1005.5       1007.0         2         7     13.5     14.1
4         1018.3       1018.5         7         7     11.1     15.4
..           ...          ...       ...       ...      ...      ...
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM RainTomorrow
0           No      3.6          Yes
1          Yes      3.6          Yes
2          Yes     39.8          Yes
3          Yes      2.8          Yes
4          Yes      0.0           No
..         ...      ...          ...
361         No      0.0           No
362         No      0.0           No
363         No      0.0           No
364         No      0.0           No
365         No      0.0           No

[366 rows x 22 columns]>

In [32]:
data.Evaporation.std()

2.6693825342212665

# Q8 what is variance of "Humidity9am"

In [34]:
data.Humidity3pm.var()

283.95442772662614

# Q.9 Find all instances when "Sunshine is above 10 and wind speed3am=10"

In [35]:
(data.head)

<bound method NDFrame.head of      MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW
1       14.0     26.9       3.6          4.4       9.7         ENE
2       13.7     23.4       3.6          5.8       3.3          NW
3       13.3     15.5      39.8          7.2       9.1          NW
4        7.6     16.1       2.8          5.6      10.6         SSE
..       ...      ...       ...          ...       ...         ...
361      9.0     30.7       0.0          7.6      12.1         NNW
362      7.1     28.4       0.0         11.6      12.7           N
363     12.5     19.9       0.0          8.4       5.3         ESE
364     12.5     26.9       0.0          5.0       7.1          NW
365     12.3     30.2       0.0          6.0      12.6          NW

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29
1             39.0          E          W           4.0  ...           36
2             85.0          N        NNE           6.0  ...           69
3             54.0        WNW          W          30.0  ...           56
4             50.0        SSE        ESE          20.0  ...           49
..             ...        ...        ...           ...  ...          ...
361           76.0        SSE         NW           7.0  ...           15
362           48.0        NNW        NNW           2.0  ...           22
363           43.0        ENE        ENE          11.0  ...           47
364           46.0        SSW        WNW           6.0  ...           39
365           78.0         NW        WNW          31.0  ...           13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6
1         1012.4       1008.4         5         3     17.5     25.7
2         1009.5       1007.2         8         7     15.4     20.2
3         1005.5       1007.0         2         7     13.5     14.1
4         1018.3       1018.5         7         7     11.1     15.4
..           ...          ...       ...       ...      ...      ...
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM RainTomorrow
0           No      3.6          Yes
1          Yes      3.6          Yes
2          Yes     39.8          Yes
3          Yes      2.8          Yes
4          Yes      0.0           No
..         ...      ...          ...
361         No      0.0           No
362         No      0.0           No
363         No      0.0           No
364         No      0.0           No
365         No      0.0           No

[366 rows x 22 columns]>

In [44]:
data[(data["Rainfall"]>10)&(data["WindSpeed9am"]==10)]

Empty DataFrame
Columns: [MinTemp, MaxTemp, Rainfall, Evaporation, Sunshine, WindGustDir, WindGustSpeed, WindDir9am, WindDir3pm, WindSpeed9am, WindSpeed3pm, Humidity9am, Humidity3pm, Pressure9am, Pressure3pm, Cloud9am, Cloud3pm, Temp9am, Temp3pm, RainToday, RISK_MM, RainTomorrow]
Index: []

[0 rows x 22 columns]

# Q.14 what is the mean value of each colimn against each "Rainfall"

In [48]:
data.Rainfall.mean()

1.4284153005464482

# Q.10 what is the max and min value of each colimn against each "Rainfall"

In [51]:
data.Rainfall.max()

39.8

In [52]:
data.Rainfall.min()

0.0

# Q.11 show aii records where RainToday==Yes

In [16]:
data[data['RainToday']=='Yes']

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,Yes,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,Yes,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,Yes,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,Yes,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,Yes,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,Yes,0.0,No

# Q 12 Find all instances when   "Rain Tomorrow ==YEs" or "humidity3pm" is grrater than 50

In [33]:
data[(data['RainTomorrow']=='Yes') |(data['Humidity3pm']>50)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,Yes,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,Yes,0.2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,16.8,28.9,0.0,10.0,10.8,NNW,70.0,NW,NW,31.0,...,22,1016.3,1011.8,1,1,22.5,28.4,Yes,7.6,Yes
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
340,11.2,18.0,0.0,4.8,8.4,W,65.0,N,W,24.0,...,40,1009.5,1005.3,5,4,12.8,16.2,Yes,8.2,Yes
347,6.7,26.1,0.0,6.2,7.5,SSW,70.0,NE,NNW,6.0,...,47,1020.9,1016.0,4,7,16.3,23.2,Yes,13.2,Yes
348,11.9,21.1,13.2,6.6,NaN,NW,41.0,NNE,N,7.0,...,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No

In [13]:
data.head(2)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,Yes,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes

# Q13 find all instances when "WindDir3pm"and "WindDir9am"is greater than 10 or humidity <10

In [36]:
data[(data['WindDir3pm']== 'W')& (data['WindDir9am']=='E')| (data['Humidity3pm']<10)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes